osc_color=#000000
window_title_color=#FFFFFF
window_controls_color=#c9c4d3
window_controls_close_hover=#ffb4ab
window_controls_minmax_hover=#d3bfe6
title_color=#FFFFFF
seekbarfg_color=#c9beff
seekbarbg_color=#484551
seekbar_cache_color=#d3bfe6
volumebar_match_seek_color=no
time_color=#e6e0ef
chapter_title_color=#c9c4d3
chapter_marker_color=#e4b8eb
chapter_marker_current_color=#c9beff
side_buttons_color=#c9c4d3
middle_buttons_color=#e6e0ef
playpause_color=#c9beff
held_element_color=#938f9c
hover_effect_color=#FFFFFF
thumbnail_border_color=#c9beff
thumbnail_border_outline=#FFFFFF

show_on_pause=no
ontop_button=no
seek_handle_size=0
show_youtube_comments=yes
FORCE_fix_not_ontop=no
