osc_color=#000000
window_title_color=#FFFFFF
window_controls_color=#c3c5dd
window_controls_close_hover=#ffb4ab
window_controls_minmax_hover=#8ad0ee
title_color=#FFFFFF
seekbarfg_color=#61d4ff
seekbarbg_color=#424659
seekbar_cache_color=#8ad0ee
volumebar_match_seek_color=no
time_color=#e2e1ef
chapter_title_color=#c3c5dd
chapter_marker_color=#b8c3ff
chapter_marker_current_color=#61d4ff
side_buttons_color=#c3c5dd
middle_buttons_color=#e2e1ef
playpause_color=#61d4ff
held_element_color=#8d8fa6
hover_effect_color=#FFFFFF
thumbnail_border_color=#61d4ff
thumbnail_border_outline=#FFFFFF

show_on_pause=no
ontop_button=no
seek_handle_size=0
show_youtube_comments=yes
FORCE_fix_not_ontop=no
