osc_color=#000000
window_title_color=#FFFFFF
window_controls_color=#becabe
window_controls_close_hover=#ffb4ab
window_controls_minmax_hover=#a3d0bf
title_color=#FFFFFF
seekbarfg_color=#00e38c
seekbarbg_color=#3e4941
seekbar_cache_color=#a3d0bf
volumebar_match_seek_color=no
time_color=#dae6da
chapter_title_color=#becabe
chapter_marker_color=#8dd3cb
chapter_marker_current_color=#00e38c
side_buttons_color=#becabe
middle_buttons_color=#dae6da
playpause_color=#00e38c
held_element_color=#889489
hover_effect_color=#FFFFFF
thumbnail_border_color=#00e38c
thumbnail_border_outline=#FFFFFF

show_on_pause=no
ontop_button=no
layout_option=reduced
seek_handle_size=0
show_youtube_comments=yes
FORCE_fix_not_ontop=no
window_controls_title=${filename}


show_on_pause=no
ontop_button=no
seek_handle_size=0
show_youtube_comments=yes
FORCE_fix_not_ontop=no
